// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DidacticalEnigma.Mem.Client.MemApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AddTranslationParams
    {
        /// <summary>
        /// Initializes a new instance of the AddTranslationParams class.
        /// </summary>
        public AddTranslationParams()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AddTranslationParams class.
        /// </summary>
        public AddTranslationParams(string source = default(string), string target = default(string), string correlationId = default(string), System.Guid? categoryId = default(System.Guid?), AddTranslationNotesParams translationNotes = default(AddTranslationNotesParams), IDictionary<string, object> associatedData = default(IDictionary<string, object>))
        {
            Source = source;
            Target = target;
            CorrelationId = correlationId;
            CategoryId = categoryId;
            TranslationNotes = translationNotes;
            AssociatedData = associatedData;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "source")]
        public string Source { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "target")]
        public string Target { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "correlationId")]
        public string CorrelationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryId")]
        public System.Guid? CategoryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "translationNotes")]
        public AddTranslationNotesParams TranslationNotes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "associatedData")]
        public IDictionary<string, object> AssociatedData { get; set; }

    }
}
