// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DidacticalEnigma.Mem.Client.MemApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AddTranslationsParams
    {
        /// <summary>
        /// Initializes a new instance of the AddTranslationsParams class.
        /// </summary>
        public AddTranslationsParams()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AddTranslationsParams class.
        /// </summary>
        /// <param name="allowPartialAdd">Controls whether to add translations
        /// if only a part of them could be inserted (because the correlation
        /// ids of others are already added for the project)</param>
        public AddTranslationsParams(bool? allowPartialAdd = default(bool?), IList<AddTranslationParams> translations = default(IList<AddTranslationParams>))
        {
            AllowPartialAdd = allowPartialAdd;
            Translations = translations;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets controls whether to add translations if only a part of
        /// them could be inserted (because the correlation ids of others are
        /// already added for the project)
        /// </summary>
        [JsonProperty(PropertyName = "allowPartialAdd")]
        public bool? AllowPartialAdd { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "translations")]
        public IList<AddTranslationParams> Translations { get; set; }

    }
}
