// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DidacticalEnigma.Mem.Client.MemApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class QueryInvitationSentResult
    {
        /// <summary>
        /// Initializes a new instance of the QueryInvitationSentResult class.
        /// </summary>
        public QueryInvitationSentResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the QueryInvitationSentResult class.
        /// </summary>
        public QueryInvitationSentResult(string projectName = default(string), string invitedUser = default(string))
        {
            ProjectName = projectName;
            InvitedUser = invitedUser;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "projectName")]
        public string ProjectName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "invitedUser")]
        public string InvitedUser { get; set; }

    }
}
