// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DidacticalEnigma.Mem.Client.MemApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class QueryContextResult
    {
        /// <summary>
        /// Initializes a new instance of the QueryContextResult class.
        /// </summary>
        public QueryContextResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the QueryContextResult class.
        /// </summary>
        public QueryContextResult(System.Guid? id = default(System.Guid?), string text = default(string), string correlationId = default(string), string mediaType = default(string), string projectName = default(string), bool? hasData = default(bool?))
        {
            Id = id;
            Text = text;
            CorrelationId = correlationId;
            MediaType = mediaType;
            ProjectName = projectName;
            HasData = hasData;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "text")]
        public string Text { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "correlationId")]
        public string CorrelationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mediaType")]
        public string MediaType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "projectName")]
        public string ProjectName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hasData")]
        public bool? HasData { get; set; }

    }
}
