// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DidacticalEnigma.Mem.Client.MemApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class QueryContextsResult
    {
        /// <summary>
        /// Initializes a new instance of the QueryContextsResult class.
        /// </summary>
        public QueryContextsResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the QueryContextsResult class.
        /// </summary>
        public QueryContextsResult(IList<QueryContextResult> contexts = default(IList<QueryContextResult>))
        {
            Contexts = contexts;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contexts")]
        public IList<QueryContextResult> Contexts { get; set; }

    }
}
