// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MagicTranslatorProjectMemImporter.MemApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AddCategoriesParams
    {
        /// <summary>
        /// Initializes a new instance of the AddCategoriesParams class.
        /// </summary>
        public AddCategoriesParams()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AddCategoriesParams class.
        /// </summary>
        public AddCategoriesParams(IList<AddCategoryParams> categories = default(IList<AddCategoryParams>))
        {
            Categories = categories;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categories")]
        public IList<AddCategoryParams> Categories { get; set; }

    }
}
