// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MagicTranslatorProjectMemImporter.MemApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AddContextsParams
    {
        /// <summary>
        /// Initializes a new instance of the AddContextsParams class.
        /// </summary>
        public AddContextsParams()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AddContextsParams class.
        /// </summary>
        public AddContextsParams(IList<AddContextParams> contexts = default(IList<AddContextParams>))
        {
            Contexts = contexts;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contexts")]
        public IList<AddContextParams> Contexts { get; set; }

    }
}
