// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MagicTranslatorProjectMemImporter.MemApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class IoNormalNote
    {
        /// <summary>
        /// Initializes a new instance of the IoNormalNote class.
        /// </summary>
        public IoNormalNote()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IoNormalNote class.
        /// </summary>
        public IoNormalNote(string sideText = default(string), string text = default(string))
        {
            SideText = sideText;
            Text = text;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sideText")]
        public string SideText { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "text")]
        public string Text { get; set; }

    }
}
