// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MagicTranslatorProjectMemImporter.MemApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class QueryCategoryResult
    {
        /// <summary>
        /// Initializes a new instance of the QueryCategoryResult class.
        /// </summary>
        public QueryCategoryResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the QueryCategoryResult class.
        /// </summary>
        public QueryCategoryResult(System.Guid? id = default(System.Guid?), string name = default(string))
        {
            Id = id;
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
