// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MagicTranslatorProjectMemImporter.MemApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class QueryTranslationResult
    {
        /// <summary>
        /// Initializes a new instance of the QueryTranslationResult class.
        /// </summary>
        public QueryTranslationResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the QueryTranslationResult class.
        /// </summary>
        public QueryTranslationResult(string projectName = default(string), string source = default(string), string target = default(string), string highlighterSequence = default(string), string category = default(string), System.Guid? categoryId = default(System.Guid?), string correlationId = default(string), QueryTranslationNotesResult translationNotes = default(QueryTranslationNotesResult), IDictionary<string, object> associatedData = default(IDictionary<string, object>))
        {
            ProjectName = projectName;
            Source = source;
            Target = target;
            HighlighterSequence = highlighterSequence;
            Category = category;
            CategoryId = categoryId;
            CorrelationId = correlationId;
            TranslationNotes = translationNotes;
            AssociatedData = associatedData;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "projectName")]
        public string ProjectName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "source")]
        public string Source { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "target")]
        public string Target { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "highlighterSequence")]
        public string HighlighterSequence { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "category")]
        public string Category { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryId")]
        public System.Guid? CategoryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "correlationId")]
        public string CorrelationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "translationNotes")]
        public QueryTranslationNotesResult TranslationNotes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "associatedData")]
        public IDictionary<string, object> AssociatedData { get; set; }

    }
}
