// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MagicTranslatorProjectMemImporter.MemApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class UpdateTranslationParams
    {
        /// <summary>
        /// Initializes a new instance of the UpdateTranslationParams class.
        /// </summary>
        public UpdateTranslationParams()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UpdateTranslationParams class.
        /// </summary>
        public UpdateTranslationParams(string source = default(string), string target = default(string), System.Guid? categoryId = default(System.Guid?), UpdateTranslationNotesParams translationNotes = default(UpdateTranslationNotesParams), IDictionary<string, object> associatedData = default(IDictionary<string, object>), System.DateTime? lastQueryTime = default(System.DateTime?))
        {
            Source = source;
            Target = target;
            CategoryId = categoryId;
            TranslationNotes = translationNotes;
            AssociatedData = associatedData;
            LastQueryTime = lastQueryTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "source")]
        public string Source { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "target")]
        public string Target { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryId")]
        public System.Guid? CategoryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "translationNotes")]
        public UpdateTranslationNotesParams TranslationNotes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "associatedData")]
        public IDictionary<string, object> AssociatedData { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastQueryTime")]
        public System.DateTime? LastQueryTime { get; set; }

    }
}
