// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MagicTranslatorProjectMemImporter.MemApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class UpdateTranslationNotesParams
    {
        /// <summary>
        /// Initializes a new instance of the UpdateTranslationNotesParams
        /// class.
        /// </summary>
        public UpdateTranslationNotesParams()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UpdateTranslationNotesParams
        /// class.
        /// </summary>
        public UpdateTranslationNotesParams(IList<IoNormalNote> normal = default(IList<IoNormalNote>), IList<IoGlossNote> gloss = default(IList<IoGlossNote>))
        {
            Normal = normal;
            Gloss = gloss;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "normal")]
        public IList<IoNormalNote> Normal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "gloss")]
        public IList<IoGlossNote> Gloss { get; set; }

    }
}
