// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MagicTranslatorProjectMemImporter.MemApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AddTranslation
    {
        /// <summary>
        /// Initializes a new instance of the AddTranslation class.
        /// </summary>
        public AddTranslation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AddTranslation class.
        /// </summary>
        public AddTranslation(string source = default(string), string target = default(string), string correlationId = default(string), System.Guid? context = default(System.Guid?))
        {
            Source = source;
            Target = target;
            CorrelationId = correlationId;
            Context = context;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "source")]
        public string Source { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "target")]
        public string Target { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "correlationId")]
        public string CorrelationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "context")]
        public System.Guid? Context { get; set; }

    }
}
