// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MagicTranslatorProjectMemImporter.MemApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AddTranslations
    {
        /// <summary>
        /// Initializes a new instance of the AddTranslations class.
        /// </summary>
        public AddTranslations()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AddTranslations class.
        /// </summary>
        public AddTranslations(IList<AddContext> contexts = default(IList<AddContext>), IList<AddTranslation> translations = default(IList<AddTranslation>))
        {
            Contexts = contexts;
            Translations = translations;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contexts")]
        public IList<AddContext> Contexts { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "translations")]
        public IList<AddTranslation> Translations { get; set; }

    }
}
