// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MagicTranslatorProjectMemImporter.MemApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class QueryTranslationResult
    {
        /// <summary>
        /// Initializes a new instance of the QueryTranslationResult class.
        /// </summary>
        public QueryTranslationResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the QueryTranslationResult class.
        /// </summary>
        public QueryTranslationResult(string projectName = default(string), string source = default(string), string target = default(string), string highlighterSequence = default(string), string correlationId = default(string), System.Guid? context = default(System.Guid?))
        {
            ProjectName = projectName;
            Source = source;
            Target = target;
            HighlighterSequence = highlighterSequence;
            CorrelationId = correlationId;
            Context = context;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "projectName")]
        public string ProjectName { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "source")]
        public string Source { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "target")]
        public string Target { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "highlighterSequence")]
        public string HighlighterSequence { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "correlationId")]
        public string CorrelationId { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "context")]
        public System.Guid? Context { get; private set; }

    }
}
